import pyautogui as gui
import os
import time

screenWidth, screenHeight=gui.size()
print(screenWidth, screenHeight)
gui.moveTo(5, screenHeight-5)
gui.click()
gui.typewrite('Chrome', interval=0.25)
gui.press('enter')
time.sleep(1) 
gui.moveTo(screenWidth/3,screenHeight/2)
gui.click()
try:
    Maximize=gui.locateCenterOnScreen('D:\Michal\Projects_python\Git\PyAutoGui_project\Maximize.png') 
    time.sleep(4)
    gui.moveTo(Maximize)
    gui.click()
except:
    pass
Link=gui.locateCenterOnScreen('D:\Michal\Projects_python\Git\PyAutoGui_project\http_chrome.png')
gui.moveTo(Link)
gui.moveTo(screenWidth/3,70)
gui.click()
gui.press('delete')
gui.typewrite('olx.pl/d/nowe-ogloszenie/edit/692803817/?bs=myaccount_edit&ref%5B0%5D%5Baction%5D=myaccount&ref%5B0%5D%5Bmethod%5D=index')
gui.press('enter')
gui.moveTo(screenWidth/3,screenHeight/2)
time.sleep(7)
gui.scroll(-1080)
gui.click()
gui.hotkey('ctrl','a')
time.sleep(0.5)
gui.hotkey('ctrl','c')
gui.press('delete')
time.sleep(0.5)
gui.click()
gui.hotkey('ctrl','v')
gui.press(' ')
time.sleep(0.5)
gui.scroll(-1080*2)
time.sleep(0.1)
Zgoda=gui.locateCenterOnScreen('D:\Michal\Projects_python\Git\PyAutoGui_project\Zgoda.png')
gui.moveTo(Zgoda)
gui.click()
Zmien=gui.locateCenterOnScreen('D:\Michal\Projects_python\Git\PyAutoGui_project\Zmien.png')
gui.moveTo(Zmien)
gui.click()